server:
  port: 9009

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.0.192:8848}
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:192.168.0.192:8858}
        client-ip: ${SENTINEL_CLIENT_IP:192.168.0.197}
        port: ${SENTINEL_PORT:8728}
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:127.0.0.1:3306}/middleware_arena?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
