-- middleware-arena-storage 初始化 DDL
-- TODO[Seata AT]：接入 MySQL 时执行此脚本建表

-- CREATE TABLE `stock` (
--     id          BIGINT  NOT NULL AUTO_INCREMENT COMMENT '主键',
--     product_id  BIGINT  NOT NULL COMMENT '商品 ID',
--     quantity    INT     NOT NULL DEFAULT 0 COMMENT '库存数量',
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_product_id (product_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存表';

-- Seata AT 模式必须的 undo_log 表（每个业务库都需要）
-- CREATE TABLE `undo_log` (
--     id            BIGINT       NOT NULL AUTO_INCREMENT,
--     branch_id     BIGINT       NOT NULL,
--     xid           VARCHAR(128) NOT NULL,
--     context       VARCHAR(128) NOT NULL,
--     rollback_info LONGBLOB     NOT NULL,
--     log_status    INT          NOT NULL,
--     log_created   DATETIME     NOT NULL,
--     log_modified  DATETIME     NOT NULL,
--     PRIMARY KEY (id),
--     UNIQUE KEY ux_undo_log (xid, branch_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Seata AT undo_log';
