-- 将早期“仅记录点赞行”的物理分片表升级为当前“带状态 + version”的最终一致模型。
-- 仅针对旧表执行一次；全新环境直接执行 init_like_shards.sql 中的最新建表语句。

ALTER TABLE ma_community.community_post
    ADD COLUMN like_version BIGINT NOT NULL DEFAULT 0 COMMENT '最近已持久化点赞事件版本' AFTER like_count;

ALTER TABLE ma_community_ds0.post_like_0
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE ma_community_ds0.post_like_1
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE ma_community_ds0.post_like_2
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE ma_community_ds0.post_like_3
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE ma_community_ds1.post_like_0
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE ma_community_ds1.post_like_1
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE ma_community_ds1.post_like_2
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE ma_community_ds1.post_like_3
    ADD COLUMN liked TINYINT(1) NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER liked,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
