databaseName: ma_community_logic

dataSources:
  ds_meta:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: $${MYSQL_META_URL::jdbc:mysql://127.0.0.1:3306/ma_community?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai}
    username: $${MYSQL_USER::root}
    password: $${MYSQL_PASSWORD::root}
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: $${MYSQL_LIKE_DS0_URL::jdbc:mysql://127.0.0.1:3306/ma_community_ds0?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai}
    username: $${MYSQL_USER::root}
    password: $${MYSQL_PASSWORD::root}
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: $${MYSQL_LIKE_DS1_URL::jdbc:mysql://127.0.0.1:3306/ma_community_ds1?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai}
    username: $${MYSQL_USER::root}
    password: $${MYSQL_PASSWORD::root}

rules:
  - !SHARDING
    tables:
      post_like:
        actualDataNodes: ds_${0..1}.post_like_${0..3}
        databaseStrategy:
          standard:
            shardingColumn: post_id
            shardingAlgorithmName: like-db-inline
        tableStrategy:
          standard:
            shardingColumn: post_id
            shardingAlgorithmName: like-table-inline
    shardingAlgorithms:
      like-db-inline:
        type: INLINE
        props:
          algorithm-expression: "ds_${post_id % 8 < 4 ? 0 : 1}"
      like-table-inline:
        type: INLINE
        props:
          algorithm-expression: "post_like_${post_id % 4}"
  - !SINGLE
    tables:
      - ds_meta.community_post
      - ds_meta.community_comment
      - ds_meta.post_favorite
      - ds_meta.community_follow
      - ds_meta.consumer_event
      - ds_meta.event_outbox
    defaultDataSource: ds_meta
props:
  sql-show: true
