server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:192.168.0.192:8848}
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:192.168.0.192:8858}
        client-ip: ${SENTINEL_CLIENT_IP:192.168.0.197}
        port: ${SENTINEL_PORT:8719}
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
        - id: experiment-service
          uri: lb://experiment-service
          predicates:
            - Path=/experiment/**
        - id: runner-service
          uri: lb://runner-service
          predicates:
            - Path=/runner/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

management:
  endpoints:
    web:
      exposure:
        include: health,info
