-- middleware-arena-runner：无持久化实体，不建表
-- 任务状态由 experiment-service 的 experiment_task 持有，
-- 压测结果由 experiment-service 的 experiment_result 持有。
-- runner 只消费 RunnerTaskMessage（MQ 契约）执行 Docker / k6 流水线并回传 progress / result。
